services:
  mcpksef:
    image: mcpksef
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PAT_TOKEN: TUTAJ_PAT_TOKEN
    container_name: mcp-ksef-container
    command: --http --use-ksef-production
    ports:
      - 8080:8080
    environment:
      - KSEF_TOKEN=Tutaj_Wklej_Token_KSeF
      - KSEF_VATID=Tutaj_Wpisz_Numer_Vat_Swojej_firmy