name: Build and Push Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5
      
      # Get the short commit hash
      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      # Log in to GitHub Docker Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Show release tag
        run: | 
          echo "Release Tag: ${{ github.event.release.tag_name }}"
      
      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --build-arg PAT_TOKEN=${{ secrets.GITHUB_TOKEN }} . --file Dockerfile --tag ghcr.io/herbat73/mcp-ksef:${{ github.event.release.tag_name }}
          docker tag ghcr.io/herbat73/mcp-ksef:${{ github.event.release.tag_name }} ghcr.io/herbat73/mcp-ksef:latest
      
      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/herbat73/mcp-ksef:${{ github.event.release.tag_name }}
          docker push ghcr.io/herbat73/mcp-ksef:latest
